###############################################################################
## dev 开发环境
###############################################################################
## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #password : 123456
    password: hhpXEF1+FPDpRbqzTFuAlbyv7La/gy42E+7leKdTgOqVj7H32i2gHxpuD9aOlMtULdwCMcwrR+QqgDmGoAWCVQ==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJYTAJZ79FBOX+Hm053xAApetyzPSM/0JyLqG2V8mLIfyGd7rouhIaiqJXddIJAwvcv6ZZ+bvPdFMpudZQjEmCkCAwEAAQ==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
###############################################################################
## redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
###############################################################################
## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml
###############################################################################
## swagger配置
swagger:
  enable: true
###############################################################################
